### PR TITLE
Change programs theme to dark

### PR DESCRIPTION
**Pull request by frxctura**
Hey there! 

I personally really cannot stand the default WinForms look of white and old so I gave the design my own small spin and made it entirely dark themed, I hope this PR is useful to ya.

- All text changed to pure white.
- All controls were given the 20;20;20 BackColor when possible.
- All controls changed to FlatStyle Flat when possible.
- All controls changed to have BorderStyle FixedSingle when possible.
- Logo changed to be adjusted to dark theme.
- Adjusted some control sizes.

### CODE REVIEW

**Comment by Chax1** [comment]
Apologies, I have noticed I commited my own language into the program, will fix ASAP.

**Comment by frxctura** [comment]
In any case if you do not want this to be the main theme, create a new branch and I will adjust my PR to point towards the branch.

**Comment by Masquerade64** [comment]
Thanks for the work. I'll try to add a dark theme setting soon.

**Comment by frxctura** [comment]
No worries!

**Pull request closed without merging**
